{
 "title": "WasteLens Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Confiance moyenne",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wastelens_confidence_score_sum / wastelens_confidence_score_count\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latence moyenne /predict",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=\"/predict\"}[5m]) / rate(http_request_duration_seconds_count{handler=\"/predict\"}[5m])",
     "legendFormat": "Latence moyenne"
    }
   ]
  },
  {
   "title": "Requêtes par endpoints",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{handler!=\"/metrics\",handler!=\"none\",handler!=\"/openapi.json\",handler!=\"/docs\"}",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Prédictions par classes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wastelens_predictions_total", "legendFormat": "{{predicted_class}}" }
   ]
  }
 ]
}